import type {
  AppNotification,
  Beneficiary,
  Biller,
  DpsEnrollment,
  DpsScheme,
  NotificationPreferences,
  RecurringRemittance,
  SavingsAccount,
  SupportTicket,
  Transaction,
  User,
} from "../types";

const DAY = 86400000;
const now = Date.now();
const iso = (offsetDays: number, offsetHours = 0) =>
  new Date(now + offsetDays * DAY + offsetHours * 3600000).toISOString();

export const CURRENT_FX_RATE = 19.8452;

export const seedUser: User = {
  id: "usr_1",
  fullName: "Md. Rahim Uddin",
  mobileNumber: "+60 11-2345 6789",
  email: "rahim.uddin@gmail.com",
  malaysiaAddress: {
    line1: "Block C-3-12, Pangsapuri Sri Melur, Jalan Meru",
    postalCode: "41050",
    country: "Malaysia",
  },
  bangladeshAddress: {
    line1: "Village: Char Kukri Mukri, Post Office: Charfasson",
    division: "Barisal",
    district: "Bhola",
    upazila: "Charfasson",
    postalCode: "8130",
    country: "Bangladesh",
  },
  occupation: "Machine Operator",
  employer: "Kluang Precision Manufacturing Sdn. Bhd.",
  incomeBand: "RM 2,000 – RM 3,000 / month",
  nidNumber: "1994 6273 8810",
  workPermitNumber: "WP-MY-88213047",
  workPermitExpiry: iso(94),
  kycStatus: "verified",
  riskTier: "standard",
  language: "en",
  memberSince: iso(-612),
  dailyLimitMyr: 8000,
  monthlyLimitMyr: 40000,
  dailyUsedMyr: 350,
  monthlyUsedMyr: 6420,
};

export const seedBeneficiaries: Beneficiary[] = [
  {
    id: "ben_1",
    type: "bank",
    fullName: "Shirin Akter",
    relationship: "Spouse",
    isDefault: true,
    isActive: true,
    screeningStatus: "cleared",
    createdAt: iso(-600),
    bankName: "Islami Bank Bangladesh",
    branchName: "Charfasson Branch",
    routingNumber: "125174520",
    accountNumber: "2014 5590 1123",
  },
  {
    id: "ben_2",
    type: "mfs",
    fullName: "Abdul Karim (Father)",
    relationship: "Father",
    isActive: true,
    screeningStatus: "cleared",
    createdAt: iso(-540),
    mfsProvider: "bKash",
    mobileNumber: "+880 1712-345678",
  },
  {
    id: "ben_3",
    type: "bank",
    fullName: "Nasrin Sultana",
    relationship: "Sister",
    isActive: true,
    screeningStatus: "cleared",
    createdAt: iso(-320),
    bankName: "Sonali Bank",
    branchName: "Bhola Sadar Branch",
    routingNumber: "200272809",
    accountNumber: "3390 8821 004",
  },
  {
    id: "ben_4",
    type: "cash_pickup",
    fullName: "Md. Jashim Uddin",
    relationship: "Uncle",
    isActive: true,
    screeningStatus: "cleared",
    createdAt: iso(-120),
    pickupNetwork: "Bkash Cash Point Network",
    pickupRegion: "Bhola District",
  },
];

export const seedTransactions: Transaction[] = [
  {
    id: "txn_1",
    reference: "RN2607160231",
    kind: "remittance",
    status: "completed",
    createdAt: iso(-1, -3),
    beneficiaryId: "ben_1",
    beneficiaryName: "Shirin Akter",
    sendAmountMyr: 800,
    fxRate: 19.8123,
    commissionMyr: 6,
    totalAmountMyr: 806,
    receiveAmountBdt: 15849.84,
    incentiveBdt: 396.25,
    payoutMethod: "bank",
    fundingMethod: "bank_transfer",
  },
  {
    id: "txn_2",
    reference: "RN2607140118",
    kind: "bill",
    status: "completed",
    createdAt: iso(-3, -6),
    billerName: "DESCO",
    billerCategory: "electricity",
    sendAmountMyr: 42.5,
    fxRate: 19.799,
    commissionMyr: 1.5,
    totalAmountMyr: 44,
    receiveAmountBdt: 841.46,
    fundingMethod: "card",
  },
  {
    id: "txn_3",
    reference: "RN2607120097",
    kind: "dps_contribution",
    status: "completed",
    createdAt: iso(-5, -1),
    beneficiaryName: "Islami Bank DPS",
    sendAmountMyr: 101,
    fxRate: 19.802,
    commissionMyr: 0,
    totalAmountMyr: 101,
    receiveAmountBdt: 2000,
    fundingMethod: "bank_transfer",
  },
  {
    id: "txn_4",
    reference: "RN2607090045",
    kind: "remittance",
    status: "completed",
    createdAt: iso(-8, -4),
    beneficiaryId: "ben_2",
    beneficiaryName: "Abdul Karim (Father)",
    sendAmountMyr: 500,
    fxRate: 19.788,
    commissionMyr: 5,
    totalAmountMyr: 505,
    receiveAmountBdt: 9894,
    incentiveBdt: 247.35,
    payoutMethod: "mfs",
    fundingMethod: "bank_transfer",
  },
  {
    id: "txn_5",
    reference: "RN2607050012",
    kind: "bill",
    status: "failed",
    createdAt: iso(-11, -2),
    billerName: "Titas Gas",
    billerCategory: "gas",
    sendAmountMyr: 18,
    fxRate: 19.81,
    commissionMyr: 1,
    totalAmountMyr: 19,
    receiveAmountBdt: 356.58,
    fundingMethod: "card",
    notes: "Biller system timeout — amount refunded",
  },
  {
    id: "txn_6",
    reference: "RN2606280391",
    kind: "remittance",
    status: "completed",
    createdAt: iso(-18, -5),
    beneficiaryId: "ben_3",
    beneficiaryName: "Nasrin Sultana",
    sendAmountMyr: 300,
    fxRate: 19.756,
    commissionMyr: 4,
    totalAmountMyr: 304,
    receiveAmountBdt: 5926.8,
    incentiveBdt: 148.17,
    payoutMethod: "bank",
    fundingMethod: "cash_deposit",
  },
  {
    id: "txn_7",
    reference: "RN2606200287",
    kind: "savings_topup",
    status: "completed",
    createdAt: iso(-26, -7),
    beneficiaryName: "Islami Bank Savings",
    sendAmountMyr: 200,
    fxRate: 19.72,
    commissionMyr: 0,
    totalAmountMyr: 200,
    receiveAmountBdt: 3944,
    fundingMethod: "bank_transfer",
  },
  {
    id: "txn_8",
    reference: "RN2606010199",
    kind: "bill",
    status: "completed",
    createdAt: iso(-45, -1),
    billerName: "Dhaka WASA",
    billerCategory: "water",
    sendAmountMyr: 12,
    fxRate: 19.688,
    commissionMyr: 1,
    totalAmountMyr: 13,
    receiveAmountBdt: 236.26,
    fundingMethod: "card",
  },
];

export const seedRecurringRemittances: RecurringRemittance[] = [
  {
    id: "rec_1",
    beneficiaryId: "ben_1",
    beneficiaryName: "Shirin Akter",
    amountMyr: 800,
    frequency: "monthly",
    startDate: iso(-600),
    nextRunDate: iso(12),
    status: "active",
  },
];

export const seedBillers: Biller[] = [
  {
    id: "bil_1",
    category: "electricity",
    providerName: "DESCO",
    accountNumber: "DESCO-771029-4",
    label: "Home Electricity",
    lastBillAmountBdt: 940,
    lastBillDueDate: iso(6),
    supportsLiveFetch: true,
    status: "due_soon",
    autoPay: {
      enabled: true,
      mode: "fetched_capped",
      capAmountBdt: 1500,
      paymentDay: 5,
      consecutiveFailures: 0,
      paused: false,
    },
  },
  {
    id: "bil_2",
    category: "gas",
    providerName: "Titas Gas",
    accountNumber: "TG-2209-88134",
    label: "Home Gas Line",
    lastBillAmountBdt: 380,
    lastBillDueDate: iso(-4),
    supportsLiveFetch: false,
    status: "overdue",
  },
  {
    id: "bil_3",
    category: "water",
    providerName: "Dhaka WASA",
    accountNumber: "WASA-004421",
    label: "Water & Sewerage",
    lastBillAmountBdt: 236,
    lastBillDueDate: iso(18),
    supportsLiveFetch: true,
    status: "up_to_date",
  },
  {
    id: "bil_4",
    category: "internet",
    providerName: "Link3 Broadband",
    accountNumber: "L3-BB-55291",
    label: "Home Internet",
    lastBillAmountBdt: 1200,
    lastBillDueDate: iso(22),
    supportsLiveFetch: false,
    status: "up_to_date",
  },
  {
    id: "bil_5",
    category: "mobile",
    providerName: "Grameenphone",
    accountNumber: "01712-345678",
    label: "Mother's Number",
    supportsLiveFetch: false,
    status: "up_to_date",
  },
];

export const seedSavingsAccounts: SavingsAccount[] = [
  {
    id: "sav_1",
    partnerBank: "Islami Bank Bangladesh",
    accountNumber: "2014 5590 8834",
    accountType: "Mudaraba Savings",
    balanceBdt: 184620,
    lastSyncedAt: iso(0, -2),
    linkedAt: iso(-540),
  },
];

export const seedDpsSchemes: DpsScheme[] = [
  {
    id: "dps_scheme_1",
    partnerBank: "Islami Bank Bangladesh",
    schemeName: "Mudaraba Monthly DPS",
    tenureYears: 5,
    monthlyInstallmentBdt: 2000,
    indicativeRatePct: 6.5,
    minEligibility: "Valid NID, active Islami Bank savings account",
  },
  {
    id: "dps_scheme_2",
    partnerBank: "Islami Bank Bangladesh",
    schemeName: "Mudaraba Monthly DPS",
    tenureYears: 10,
    monthlyInstallmentBdt: 2000,
    indicativeRatePct: 6.75,
    minEligibility: "Valid NID, active Islami Bank savings account",
  },
  {
    id: "dps_scheme_3",
    partnerBank: "Dutch-Bangla Bank",
    schemeName: "DBBL Monthly Savings Scheme",
    tenureYears: 3,
    monthlyInstallmentBdt: 1000,
    indicativeRatePct: 6.0,
    minEligibility: "Valid NID",
  },
  {
    id: "dps_scheme_4",
    partnerBank: "Dutch-Bangla Bank",
    schemeName: "DBBL Monthly Savings Scheme",
    tenureYears: 5,
    monthlyInstallmentBdt: 5000,
    indicativeRatePct: 6.35,
    minEligibility: "Valid NID",
  },
  {
    id: "dps_scheme_5",
    partnerBank: "BRAC Bank",
    schemeName: "Priyo DPS",
    tenureYears: 3,
    monthlyInstallmentBdt: 500,
    indicativeRatePct: 5.75,
    minEligibility: "Valid NID, minimum 1 month account tenure",
  },
];

export const seedDpsEnrollments: DpsEnrollment[] = [
  {
    id: "dps_1",
    schemeId: "dps_scheme_1",
    partnerBank: "Islami Bank Bangladesh",
    schemeName: "Mudaraba Monthly DPS",
    tenureYears: 5,
    monthlyInstallmentBdt: 2000,
    indicativeRatePct: 6.5,
    nominee: "Shirin Akter (Spouse)",
    startDate: iso(-360),
    maturityDate: iso(1461),
    contributedToDateBdt: 24000,
    indicativeMaturityValueBdt: 141230,
    status: "active",
    autoContribution: {
      enabled: true,
      amountMyr: 101,
      nextRunDate: iso(18),
    },
  },
];

export const seedNotifications: AppNotification[] = [
  {
    id: "notif_1",
    category: "transaction",
    title: "Remittance delivered",
    body: "Your RM800 transfer to Shirin Akter was credited successfully.",
    createdAt: iso(-1, -3),
    read: false,
  },
  {
    id: "notif_2",
    category: "reminder",
    title: "DESCO bill due in 6 days",
    body: "Estimated ৳940 will be auto-paid on 5th from your linked funding source.",
    createdAt: iso(-1),
    read: false,
  },
  {
    id: "notif_3",
    category: "nestegg",
    title: "Nest Egg milestone reached",
    body: "You've crossed ৳2,00,000 in combined savings and DPS contributions. Great progress!",
    createdAt: iso(-4),
    read: true,
  },
  {
    id: "notif_4",
    category: "compliance",
    title: "Work permit renewal reminder",
    body: "Your Malaysian work permit expires in 94 days. Upload your renewed permit when ready.",
    createdAt: iso(-6),
    read: true,
  },
  {
    id: "notif_5",
    category: "security",
    title: "New device login",
    body: "Your account was accessed from a new Android device in Kluang, Johor.",
    createdAt: iso(-10),
    read: true,
  },
];

export const seedTickets: SupportTicket[] = [
  {
    id: "tic_1",
    reference: "SUP-88213",
    subject: "Gas bill payment failed but amount was deducted",
    status: "resolved",
    createdAt: iso(-10),
    relatedTransactionId: "txn_5",
    slaTarget: iso(-8),
    messages: [
      { from: "user", text: "My Titas Gas payment failed but RM19 was deducted from my account.", at: iso(-10) },
      { from: "support", text: "Thanks for reporting this — we've confirmed the biller timeout and reversed the debit. It should reflect within 24 hours.", at: iso(-9) },
      { from: "user", text: "Received the refund, thank you!", at: iso(-8) },
    ],
  },
];

export const defaultNotificationPreferences: NotificationPreferences = {
  security: { push: true, sms: true, email: false },
  transaction: { push: true, sms: false, email: true },
  reminder: { push: true, sms: true, email: false },
  compliance: { push: true, sms: false, email: true },
  nestegg: { push: true, sms: false, email: false },
  promotional: { push: false, sms: false, email: false },
};

export function genReference(prefix = "RN"): string {
  const d = new Date();
  const stamp = `${d.getFullYear().toString().slice(2)}${String(d.getMonth() + 1).padStart(2, "0")}${String(d.getDate()).padStart(2, "0")}`;
  const rand = Math.floor(1000 + Math.random() * 9000);
  return `${prefix}${stamp}${rand}`;
}

export function genId(prefix: string): string {
  return `${prefix}_${Math.random().toString(36).slice(2, 10)}`;
}
